name: Test deployment

on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: yarn
      - name: Test build
        working-directory: documentation
        run: |
          yarn install --frozen-lockfile
          yarn build
